console.log('Hello World!');
console.log('Wellcome!');
let years = 20;
let height = 182;
let city = 'Londrina';
let name = 'Matheus';
console.log(name);
console.log(years);
console.log(height);
console.log(city);